"""initial schema

Revision ID: 3634d974da39
Revises: 
Create Date: 2026-07-07 14:00:52.541731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3634d974da39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('broker', sa.Enum('KITE', 'SIMULATION', name='brokername_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('broker_client_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('broker', 'broker_client_id', name='uq_accounts_broker_client')
    )
    op.create_table('daily_risk_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('loss_limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_daily_risk_state_account_id_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_risk_state'))
    )
    op.create_index('ix_daily_risk_state_trade_date', 'daily_risk_state', ['trade_date'], unique=False)
    op.create_index('uq_daily_risk_state_instrument_row', 'daily_risk_state', ['account_id', 'instrument', 'trade_date'], unique=True, postgresql_where=sa.text('instrument IS NOT NULL'), sqlite_where=sa.text('instrument IS NOT NULL'))
    op.create_index('uq_daily_risk_state_portfolio_row', 'daily_risk_state', ['account_id', 'trade_date'], unique=True, postgresql_where=sa.text('instrument IS NULL'), sqlite_where=sa.text('instrument IS NULL'))
    op.create_table('strategy_instances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange', sa.Enum('NFO', 'BFO', name='exchange_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'DISABLED', name='instancestatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_strategy_instances_account_id_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_instances')),
    sa.UniqueConstraint('strategy_id', 'instrument', 'account_id', name='uq_strategy_instances_strategy_instrument_account')
    )
    op.create_index('ix_strategy_instances_frozen', 'strategy_instances', ['status'], unique=False, postgresql_where="status = 'FROZEN'")
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'ENTRY_PENDING', 'OPEN', 'EXIT_PENDING', 'CLOSED', 'ERROR', name='positionstate_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('strike_interval', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lots', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('entry_spot_ltp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sl_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('combined_entry_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stoploss_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('combined_exit_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_reason', sa.Enum('TARGET', 'STOPLOSS', 'TIMEOUT', 'KILL_SWITCH', 'MANUAL', 'ERROR', name='exitreason_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('entry_signal_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_signal_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('needs_reconciliation', sa.Boolean(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('exit_completed_at IS NULL OR entry_completed_at IS NULL OR exit_completed_at >= entry_completed_at', name=op.f('ck_positions_exit_after_entry')),
    sa.CheckConstraint('lot_size IS NULL OR lot_size > 0', name=op.f('ck_positions_lot_size_positive')),
    sa.CheckConstraint('lots IS NULL OR lot_size IS NULL OR quantity IS NULL OR quantity = lots * lot_size', name=op.f('ck_positions_quantity_matches_lots_times_lot_size')),
    sa.CheckConstraint('lots IS NULL OR lots > 0', name=op.f('ck_positions_lots_positive')),
    sa.CheckConstraint('quantity IS NULL OR quantity > 0', name=op.f('ck_positions_quantity_positive')),
    sa.CheckConstraint('sl_pct IS NULL OR (sl_pct > 0 AND sl_pct < 1)', name=op.f('ck_positions_sl_pct_in_range')),
    sa.CheckConstraint('target_pct IS NULL OR (target_pct > 0 AND target_pct < 1)', name=op.f('ck_positions_target_pct_in_range')),
    sa.ForeignKeyConstraint(['strategy_instance_id'], ['strategy_instances.id'], name=op.f('fk_positions_strategy_instance_id_strategy_instances'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('strategy_instance_id', 'trade_date', name='uq_positions_instance_trade_date')
    )
    op.create_index('ix_positions_active_states', 'positions', ['state'], unique=False, postgresql_where="state IN ('ENTRY_PENDING', 'OPEN', 'EXIT_PENDING', 'ERROR')")
    op.create_index('ix_positions_trade_date', 'positions', ['trade_date'], unique=False)
    op.create_table('risk_control_flags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flag_type', sa.Enum('KILL_SWITCH', 'EMERGENCY_EXIT', 'FREEZE', name='riskflagtype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'ACCOUNT', 'STRATEGY_INSTANCE', name='riskflagscope_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('strategy_instance_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('activated_by', sa.String(length=128), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.String(length=128), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("(scope = 'GLOBAL' AND account_id IS NULL AND strategy_instance_id IS NULL) OR (scope = 'ACCOUNT' AND account_id IS NOT NULL AND strategy_instance_id IS NULL) OR (scope = 'STRATEGY_INSTANCE' AND strategy_instance_id IS NOT NULL)", name=op.f('ck_risk_control_flags_scope_matches_populated_fk')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_risk_control_flags_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_instance_id'], ['strategy_instances.id'], name=op.f('fk_risk_control_flags_strategy_instance_id_strategy_instances'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_control_flags'))
    )
    op.create_index('ix_risk_control_flags_account_id', 'risk_control_flags', ['account_id'], unique=False)
    op.create_index('ix_risk_control_flags_active', 'risk_control_flags', ['active'], unique=False, postgresql_where='active = true')
    op.create_index('ix_risk_control_flags_strategy_instance_id', 'risk_control_flags', ['strategy_instance_id'], unique=False)
    op.create_table('position_state_transitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('from_state', sa.Enum('IDLE', 'ENTRY_PENDING', 'OPEN', 'EXIT_PENDING', 'CLOSED', 'ERROR', name='positionstate_from_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('to_state', sa.Enum('IDLE', 'ENTRY_PENDING', 'OPEN', 'EXIT_PENDING', 'CLOSED', 'ERROR', name='positionstate_to_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.Enum('STRATEGY', 'RISK_MANAGER', 'KILL_SWITCH', 'RECOVERY', 'MANUAL', name='statetransitionactor_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_state_transitions_position_id_positions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_state_transitions'))
    )
    op.create_index('ix_position_state_transitions_position_created', 'position_state_transitions', ['position_id', 'created_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('option_type', sa.Enum('CE', 'PE', name='optiontype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('trading_symbol', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.Enum('NFO', 'BFO', name='exchange_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'CLOSED', 'UNWOUND', 'ERROR', name='tradelegstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('entry_price IS NULL OR entry_price >= 0', name=op.f('ck_trades_entry_price_non_negative')),
    sa.CheckConstraint('exit_price IS NULL OR exit_price >= 0', name=op.f('ck_trades_exit_price_non_negative')),
    sa.CheckConstraint('exit_time IS NULL OR entry_time IS NULL OR exit_time >= entry_time', name=op.f('ck_trades_exit_after_entry')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_trades_quantity_positive')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_trades_position_id_positions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('position_id', 'option_type', 'strike', name='uq_trades_position_type_strike')
    )
    op.create_index('ix_trades_open_status', 'trades', ['status'], unique=False, postgresql_where="status = 'OPEN'")
    op.create_index('ix_trades_position_id', 'trades', ['position_id'], unique=False)
    op.create_table('order_intents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.Enum('ENTRY', 'EXIT', name='orderpurpose_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transactiontype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('broker_tag', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED_UNCONFIRMED', 'PLACED', 'CONFIRMED', 'FAILED', 'CANCELLED', name='intentstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('broker_call_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_intents_quantity_positive')),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_order_intents_trade_id_trades'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_intents')),
    sa.UniqueConstraint('broker_tag', name=op.f('uq_order_intents_broker_tag')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_order_intents_idempotency_key'))
    )
    op.create_index('ix_order_intents_in_doubt', 'order_intents', ['status'], unique=False, postgresql_where="status IN ('PENDING', 'SUBMITTED_UNCONFIRMED', 'PLACED')")
    op.create_index('ix_order_intents_trade_id', 'order_intents', ['trade_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('intent_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.Enum('ENTRY', 'EXIT', name='orderpurpose_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transactiontype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', name='ordertype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'COMPLETE', 'REJECTED', 'CANCELLED', 'ERROR', name='orderstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('broker_tag', sa.String(length=20), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('filled_quantity >= 0 AND filled_quantity <= quantity', name=op.f('ck_orders_filled_quantity_within_bounds')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_orders_retry_count_non_negative')),
    sa.ForeignKeyConstraint(['intent_id'], ['order_intents.id'], name=op.f('fk_orders_intent_id_order_intents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_orders_trade_id_trades'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('broker_order_id', name='uq_orders_broker_order_id')
    )
    op.create_index('ix_orders_in_flight', 'orders', ['status'], unique=False, postgresql_where="status IN ('PENDING', 'OPEN')")
    op.create_index('ix_orders_trade_id', 'orders', ['trade_id'], unique=False)
    op.create_table('reconciliation_breaks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('intent_id', sa.BigInteger(), nullable=True),
    sa.Column('break_type', sa.Enum('ORPHAN_FILL', 'BROKER_FLAT_DB_OPEN', 'AMBIGUOUS_ACK', 'PARTIAL_ENTRY', 'QUANTITY_MISMATCH', 'OTHER', name='reconciliationbreaktype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('broker_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.Enum('PENDING', 'AUTO_REPAIRED', 'MANUAL', name='reconciliationresolution_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['order_intents.id'], name=op.f('fk_reconciliation_breaks_intent_id_order_intents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reconciliation_breaks_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_reconciliation_breaks_position_id_positions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_breaks'))
    )
    op.create_index('ix_reconciliation_breaks_pending', 'reconciliation_breaks', ['resolution'], unique=False, postgresql_where="resolution = 'PENDING'")
    op.create_index('ix_reconciliation_breaks_position_id', 'reconciliation_breaks', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliation_breaks_position_id', table_name='reconciliation_breaks')
    op.drop_index('ix_reconciliation_breaks_pending', table_name='reconciliation_breaks', postgresql_where="resolution = 'PENDING'")
    op.drop_table('reconciliation_breaks')
    op.drop_index('ix_orders_trade_id', table_name='orders')
    op.drop_index('ix_orders_in_flight', table_name='orders', postgresql_where="status IN ('PENDING', 'OPEN')")
    op.drop_table('orders')
    op.drop_index('ix_order_intents_trade_id', table_name='order_intents')
    op.drop_index('ix_order_intents_in_doubt', table_name='order_intents', postgresql_where="status IN ('PENDING', 'SUBMITTED_UNCONFIRMED', 'PLACED')")
    op.drop_table('order_intents')
    op.drop_index('ix_trades_position_id', table_name='trades')
    op.drop_index('ix_trades_open_status', table_name='trades', postgresql_where="status = 'OPEN'")
    op.drop_table('trades')
    op.drop_index('ix_position_state_transitions_position_created', table_name='position_state_transitions')
    op.drop_table('position_state_transitions')
    op.drop_index('ix_risk_control_flags_strategy_instance_id', table_name='risk_control_flags')
    op.drop_index('ix_risk_control_flags_active', table_name='risk_control_flags', postgresql_where='active = true')
    op.drop_index('ix_risk_control_flags_account_id', table_name='risk_control_flags')
    op.drop_table('risk_control_flags')
    op.drop_index('ix_positions_trade_date', table_name='positions')
    op.drop_index('ix_positions_active_states', table_name='positions', postgresql_where="state IN ('ENTRY_PENDING', 'OPEN', 'EXIT_PENDING', 'ERROR')")
    op.drop_table('positions')
    op.drop_index('ix_strategy_instances_frozen', table_name='strategy_instances', postgresql_where="status = 'FROZEN'")
    op.drop_table('strategy_instances')
    op.drop_index('uq_daily_risk_state_portfolio_row', table_name='daily_risk_state', postgresql_where=sa.text('instrument IS NULL'), sqlite_where=sa.text('instrument IS NULL'))
    op.drop_index('uq_daily_risk_state_instrument_row', table_name='daily_risk_state', postgresql_where=sa.text('instrument IS NOT NULL'), sqlite_where=sa.text('instrument IS NOT NULL'))
    op.drop_index('ix_daily_risk_state_trade_date', table_name='daily_risk_state')
    op.drop_table('daily_risk_state')
    op.drop_table('accounts')
    # ### end Alembic commands ###
