"""add trade_history

Revision ID: c45ec4abd494
Revises: 3634d974da39
Create Date: 2026-07-16 20:35:11.300414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c45ec4abd494'
down_revision: Union[str, Sequence[str], None] = '3634d974da39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_instance_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.Enum('NFO', 'BFO', 'NSE', 'BSE', name='exchange_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('call_symbol', sa.String(length=64), nullable=True),
    sa.Column('put_symbol', sa.String(length=64), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_signal_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_signal_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holding_seconds', sa.Integer(), nullable=True),
    sa.Column('holding_minutes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lots', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('combined_entry_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('combined_exit_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stoploss_premium', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sl_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('call_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('call_exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('put_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('put_exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('entry_spot_ltp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_spot_ltp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_reason', sa.Enum('TARGET', 'STOPLOSS', 'TIMEOUT', 'KILL_SWITCH', 'MANUAL', 'ERROR', name='exitreason_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('profit_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_profit_seen', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_loss_seen', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_of_week', sa.String(length=9), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('broker_order_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_trade_history_position_id_positions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_history')),
    sa.UniqueConstraint('position_id', name=op.f('uq_trade_history_position_id'))
    )
    op.create_index('ix_trade_history_exit_reason', 'trade_history', ['exit_reason'], unique=False)
    op.create_index('ix_trade_history_expiry_date', 'trade_history', ['expiry_date'], unique=False)
    op.create_index('ix_trade_history_instrument', 'trade_history', ['instrument'], unique=False)
    op.create_index('ix_trade_history_strategy_id', 'trade_history', ['strategy_id'], unique=False)
    op.create_index('ix_trade_history_strategy_instrument_date', 'trade_history', ['strategy_id', 'instrument', 'trade_date'], unique=False)
    op.create_index('ix_trade_history_trade_date', 'trade_history', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_history_trade_date', table_name='trade_history')
    op.drop_index('ix_trade_history_strategy_instrument_date', table_name='trade_history')
    op.drop_index('ix_trade_history_strategy_id', table_name='trade_history')
    op.drop_index('ix_trade_history_instrument', table_name='trade_history')
    op.drop_index('ix_trade_history_expiry_date', table_name='trade_history')
    op.drop_index('ix_trade_history_exit_reason', table_name='trade_history')
    op.drop_table('trade_history')
    # ### end Alembic commands ###
