"""Broker abstraction layer. simulation/ and kite/ must implement broker_base.py's
interface identically, so start_paper.py and start_live.py run the same strategy
code unchanged."""

from algo.brokers.broker_base import (
    BrokerBase,
    BrokerHolding,
    BrokerInstrument,
    BrokerMargins,
    BrokerOrder,
    BrokerPosition,
    BrokerQuote,
    HealthStatus,
    InstrumentIdentifier,
    ModifyOrderRequest,
    OrderUpdateCallback,
    PlaceOrderRequest,
    PlaceOrderResult,
)
from algo.brokers.exceptions import (
    BrokerAuthenticationError,
    BrokerConnectionError,
    BrokerError,
    BrokerRateLimitExceededError,
    BrokerTimeoutError,
    InstrumentNotFoundError,
    InvalidOrderRequestError,
    NonRetryableBrokerError,
    OrderNotCancellableError,
    OrderNotFoundError,
    OrderNotModifiableError,
    OrderRejectedError,
    RetryableBrokerError,
)
from algo.brokers.rate_limiter import (
    RateLimitCategory,
    RateLimitConfig,
    RateLimitedBroker,
    RateLimitRule,
)

__all__ = [
    "BrokerBase",
    "InstrumentIdentifier",
    "BrokerInstrument",
    "PlaceOrderRequest",
    "PlaceOrderResult",
    "ModifyOrderRequest",
    "BrokerOrder",
    "OrderUpdateCallback",
    "BrokerPosition",
    "BrokerHolding",
    "BrokerMargins",
    "BrokerQuote",
    "HealthStatus",
    "BrokerError",
    "RetryableBrokerError",
    "NonRetryableBrokerError",
    "BrokerConnectionError",
    "BrokerTimeoutError",
    "BrokerRateLimitExceededError",
    "BrokerAuthenticationError",
    "OrderRejectedError",
    "OrderNotFoundError",
    "OrderNotModifiableError",
    "OrderNotCancellableError",
    "InstrumentNotFoundError",
    "InvalidOrderRequestError",
    "RateLimitCategory",
    "RateLimitRule",
    "RateLimitConfig",
    "RateLimitedBroker",
]
